server {
    listen 127.0.0.1:8443 ssl;
    http2 on;
    server_name rektstars.net www.rektstars.net;

    ssl_certificate     /etc/letsencrypt/live/rektstars.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rektstars.net/privkey.pem;


    limit_req zone=general burst=20 nodelay;
    limit_conn connlimit 20;

    root /var/www/html/rektstars;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    error_page 404 /404;
}

server {
    listen 80;
    server_name rektstars.net www.rektstars.net rektstars.i2p;

    limit_req zone=general burst=20 nodelay;
    limit_conn connlimit 20;

    root /var/www/html/rektstars;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    error_page 404 /404;
}

